### ISSUE TITLE
v1

### ISSUE THREAD

**Issue by tyrickareo** [tyrickareo/myopenideavim#1]
let mapleader=" "

"" plugin
set easymotion
set surround
set NERDTree
set ReplaceWithRegister
set argtextobj
set exchange
set textobj-entire
set vim-paragraph-motion
set textobj-indent
set matchit
set highlightedyank
set commentary
set quickscope
set multicursor

""plugin setting
let g:argtextobj_pairs="[:],(:),<:>"

""""quickscope
let g:qs_highlight_on_keys = ['f', 'F', 't', 'T']
let g:qs_accepted_chars = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
let g:qs_primary_color = '#ff0000'
let g:qs_secondary_color = '#ff00ff'

""setting
set showmode
set scrolloff=3
set incsearch
map Q gq
set clipboard^=unnamed,unnamedplus,ideaput
set ideajoin
set ideastatusicon=gray
set ignorecase smartcase
set noerrorbells
set visualbell

""key mapping
inoremap jk <ESC>`^
map s <Plug>(easymotion-s)
noremap H gT
noremap L gt

map S <Action>(EditorSelectWord)

nmap <C-I> <Action>(Forward)
nmap <C-O> <Action>(Back)

nmap <leader>a <Action>(GotoAction)
nmap <leader>rr <Action>(Rerun)
nmap <leader>rc <Action>(RunClass)
nmap <leader>rd <Action>(Debug)
nmap <leader>rs <Action>(Stop)

nmap <leader>ca <Action>(ShowIntentionActions)
nmap <leader>cc <Action>(EditorCompleteStatement)
nmap <leader>ce <Action>(ShowErrorDescription)
nmap <leader>cr <Action>(RenameElement)
nmap <leader>cp <Action>(ParameterInfo)
nmap <leader>ct <Action>(ExpressionTypeInfo)
nmap <leader>cg <Action>(Generate)

nmap <leader>bd <Action>(CloseContent)
nmap <leader>bo <Action>(CloseAllEditorsButActive)
nmap <leader>br <Action>(CloseAllToTheRight)
nmap <leader>bl <Action>(CloseAllToTheLeft)
nmap <leader>bu <Action>(ReopenClosedTab)

nmap <leader>db <Action>(ToggleLineBreakpoint)

nmap <leader>kr <Action>(leetcode.editor.RunCodeAction)
nmap <leader>ks <Action>(leetcode.editor.SubmitAction)

nmap <leader>fi <Action>(FindInPath)
nmap <leader>fu <Action>(FindUsages)
nmap <leader>fr <Action>(RecentFiles)
nmap <leader>ff <Action>(GotoFile)
nmap <leader>fc <Action>(GotoClass)
nmap <leader>fs <Action>(GotoSymbol)

nmap <leader>vi <Action>(VimFindActionIdAction)

nmap <leader>gk <Action>(CheckinProject)
nmap <leader>gK <Action>(Vcs.Push)

nmap <leader>gs <Action>(GotoSuperMethod)
nmap <leader>gi <Action>(GotoImplementation)

**Comment by tyrickareo** [comment]
#Requires AutoHotkey v2.0

; 永久禁用CapsLock功能
SetCapsLockState "AlwaysOff"

; 将CapsLock映射为Win+Space
CapsLock::Send "#{Space}"

**Comment by tyrickareo** [comment]
```
let mapleader=" "

"" plugin
set easymotion
set surround
set NERDTree
set ReplaceWithRegister
set argtextobj
set exchange
set textobj-entire
set vim-paragraph-motion
set textobj-indent
set matchit
set highlightedyank
set commentary
set quickscope
set multicursor

""plugin setting
let g:argtextobj_pairs="[:],(:),<:>"

""""quickscope
let g:qs_highlight_on_keys = ['f', 'F', 't', 'T']
let g:qs_accepted_chars = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
let g:qs_primary_color = '#ff0000'
let g:qs_secondary_color = '#ff00ff'













""setting
set showmode
set scrolloff=3
set incsearch
map Q gq
set clipboard^=unnamed,unnamedplus,ideaput
set ideajoin
set ideastatusicon=gray
set ignorecase smartcase
set noerrorbells
set visualbell


""key mapping
inoremap jk <ESC>`^
map s <Plug>(easymotion-s)
noremap H gT
noremap L gt




map S <Action>(EditorSelectWord)


nmap <C-I> <Action>(Forward)
nmap <C-O> <Action>(Back)

nmap <leader>a <Action>(GotoAction)
nmap <leader>n <Action>(GotoFile)
nmap <leader>rr <Action>(Rerun)
nmap <leader>rc <Action>(RunClass)
nmap <leader>rd <Action>(Debug)
nmap <leader>rs <Action>(Stop)

nmap <leader>ca <Action>(ShowIntentionActions)
nmap <leader>cc <Action>(EditorCompleteStatement)
nmap <leader>ce <Action>(ShowErrorDescription)
nmap <leader>cr <Action>(RenameElement)
nmap <leader>cp <Action>(ParameterInfo)
nmap <leader>ct <Action>(ExpressionTypeInfo)
nmap <leader>cg <Action>(Generate)

nmap <leader>bd <Action>(CloseContent)
nmap <leader>bo <Action>(CloseAllEditorsButActive)
nmap <leader>br <Action>(CloseAllToTheRight)
nmap <leader>bl <Action>(CloseAllToTheLeft)
nmap <leader>bu <Action>(ReopenClosedTab)

nmap <leader>db <Action>(ToggleLineBreakpoint)

nmap <leader>kr <Action>(leetcode-pro.editor.RunCodeAction)
nmap <leader>ks <Action>(leetcode-pro.editor.SubmitAction)


nmap <leader>fi <Action>(FindInPath)
nmap <leader>fu <Action>(FindUsages)
nmap <leader>fr <Action>(RecentFiles)
nmap <leader>ff <Action>(GotoFile)
nmap <leader>fc <Action>(GotoClass)
nmap <leader>fs <Action>(GotoSymbol)

nmap <leader>vi <Action>(VimFindActionIdAction)

nmap <leader>gk <Action>(CheckinProject)
nmap <leader>gK <Action>(Vcs.Push)

nmap <leader>gs <Action>(GotoSuperMethod)
nmap <leader>gi <Action>(GotoImplementation)

```

**Comment by tyrickareo** [comment]
Hi all,
Thank you all for your hard work in onboarding Copilot—it’s been amazing!
I have a quick question: Since updating VS Code to version 1.99.2, I’ve been unable to enable the new MCP feature, while some of my team members can use it. Could you let me know:

Is there a way for me to enable it? If so, how?
If not now, do you have plans to roll out this feature in the future?

Thanks in advance for your help!

**Comment by tyrickareo** [comment]
[pdf.zip](https://github.com/user-attachments/files/20347420/pdf.zip)

**Comment by tyrickareo** [comment]
[New folder (4).001.zip](https://github.com/user-attachments/files/20347530/New.folder.4.001.zip)
[New folder (4).002.zip](https://github.com/user-attachments/files/20347531/New.folder.4.002.zip)

**Comment by tyrickareo** [comment]
FROM ./qwen3.gguf


SYSTEM """
You are an AI assistant. Respond concisely and accurately.
"""


PARAMETER stop "<|im_start|>"
PARAMETER stop "<|im_end|>"


PARAMETER temperature 0.6
PARAMETER min_p 0.0
PARAMETER repeat_penalty 1.0
PARAMETER presence_penalty 1.5
PARAMETER top_k 20
PARAMETER top_p 0.95
PARAMETER num_predict 32768
PARAMETER num_ctx 40960  


TEMPLATE """
{{- $lastUserIdx := -1 -}}
{{- range $idx, $msg := .Messages -}}
{{- if eq $msg.Role "user" }}{{ $lastUserIdx = $idx }}{{ end -}}
{{- end }}
{{- if or .System .Tools }}<|im_start|>system
{{ if .System }}
{{ .System }}
{{- end }}
{{- if .Tools }}

# Tools

You may call one or more functions to assist with the user query.

You are provided with function signatures within <tools></tools> XML tags:
<tools>
{{- range .Tools }}
{"type": "function", "function": {{ .Function }}}
{{- end }}
</tools>

For each function call, return a json object with function name and arguments within <tool_call></tool_call> XML tags:
<tool_call>
{"name": <function-name>, "arguments": <args-json-object>}
</tool_call>
{{- end -}}
<|im_end|>
{{ end }}
{{- range $i, $_ := .Messages }}
{{- $last := eq (len (slice $.Messages $i)) 1 -}}
{{- if eq .Role "user" }}<|im_start|>user
{{ .Content }}
{{- if and $.IsThinkSet (eq $i $lastUserIdx) }}
   {{- if $.Think -}}
      {{- " "}}/think
   {{- else -}}
      {{- " "}}/no_think
   {{- end -}}
{{- end }}<|im_end|>
{{ else if eq .Role "assistant" }}<|im_start|>assistant
{{ if (and $.IsThinkSet (and .Thinking (or $last (gt $i $lastUserIdx)))) -}}
<think>{{ .Thinking }}</think>
{{ end -}}
{{ if .Content }}{{ .Content }}
{{- else if .ToolCalls }}<tool_call>
{{ range .ToolCalls }}{"name": "{{ .Function.Name }}", "arguments": {{ .Function.Arguments }}}
{{ end }}</tool_call>
{{- end }}{{ if not $last }}<|im_end|>
{{ end }}
{{- else if eq .Role "tool" }}<|im_start|>user
<tool_response>
{{ .Content }}
</tool_response><|im_end|>
{{ end }}
{{- if and (ne .Role "assistant") $last }}<|im_start|>assistant
{{ if and $.IsThinkSet (not $.Think) -}}
<think>

</think>

{{ end -}}
{{ end }}
{{- end }}
"""

**Comment by tyrickareo** [comment]
[file.txt](https://github.com/user-attachments/files/20533323/file.txt)

**Comment by tyrickareo** [comment]
[generated.zip](https://github.com/user-attachments/files/21088450/generated.zip)

**Comment by tyrickareo** [comment]
theme = "onedark"

[editor]
line-number = "relative"
# mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false


[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = ""
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

**Comment by tyrickareo** [comment]
```toml
theme = "onedark"

[editor]
line-number = "relative"
# mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false


[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = ""
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"


```

**Comment by tyrickareo** [comment]
```toml
theme = "onedark"

[editor]
line-number = "relative"
# mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false


[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = ""
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"




[keys.insert]
"A-x" = "normal_mode"     # Maps Alt-X to enter normal mode
j = { k = "normal_mode" } # Maps `jk` to exit insert mode



```
